[package]
name = "my-wasm-lib"
version = "0.1.0"
authors = ["sundaycrafts <sundaycrafts@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
